# Codecov configuration for goffi - Zero-CGO FFI for Go
# Documentation: https://docs.codecov.com/docs/codecovyml-reference
# Validator: https://api.codecov.io/validate

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%           # Minimum project coverage (current: 89.1%)
        threshold: 2%         # Allow 2% drop from target
        base: auto
        informational: false  # Fail if below target
        only_pulls: false

    patch:
      default:
        target: auto          # Auto-detect reasonable target for changes
        threshold: 10%        # Allow 10% variance for patches
        base: auto
        informational: true   # Don't fail PRs, just inform
        only_pulls: false

  ignore:
    - "cmd/**"                # CLI tools (not covered by tests)
    - "examples/**"           # Example code (not covered by tests)
    - "experiments/**"        # Research and prototypes (not production code)
    - "reference/**"          # External reference code (libffi, purego)
    - "docs/dev/**"           # Private development documentation
    - "testdata/**"           # Test data files
    - "**/*_test.go"          # Test files themselves
    - "tmp/**"                # Temporary files
    - "internal/testing/**"   # Test utilities (if added)

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# GitHub integration
github_checks:
  annotations: true
