version: "2"

run:
  timeout: 10m
  concurrency: 4
  modules-download-mode: readonly
  build-tags:
    - linux  #

linters:
  disable:
    - gocyclo
    - wsl
    - dupl
    - goconst
    - gocritic
    - gosec
    - funlen

  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign

  settings:
    govet:
      enable:
        - shadow

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: gen/.*\.pb\.go
        linters:
          - revive
          - govet
          - staticcheck
      - path: examples/.*
        linters:
          - revive
      - path: internal/arch/stubs
        linters:
          - govet
          - staticcheck
          - errcheck
          - ineffassign
      - path: internal/arch/amd64/.*\.s
        linters:
          - govet
      # fakecgo: Go runtime code with assembly callbacks
      - path: internal/fakecgo/
        linters:
          - unused        # Functions called from assembly
          - govet         # Low-level runtime code
          - staticcheck
          - ineffassign
      # dl: Dynamic library wrappers called from assembly
      - path: internal/dl/
        linters:
          - unused        # Wrappers called from assembly
          - staticcheck
      # FFI code: unsafe.Pointer is fundamental
      - path: ffi/dl_.*\.go
        linters:
          - govet         # unsafe.Pointer conversions are correct
      - path: internal/arch/amd64/implementation\.go
        linters:
          - govet         # unsafe.Pointer for return values
          - unused        # align() used for struct layout

issues:
  max-issues-per-linter: 100
  max-same-issues: 100